name: Pull Request Checks

env:
  AZURE_WEBAPP_NAME: asd-backend # set this to the name of your Azure Web App

on: [pull_request]

permissions:
  contents: read

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16.10.0
      - run: |
          cd frontend
          yarn install
          yarn run test -u

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16.10.0

      - name: Save test secrets
        run: |
          cd backend
          echo "DB_HOST='${{ secrets.DB_HOST }}'" >> .env
          echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> .env
          echo "ENVIRONMENT='local'" >> .env
          echo "DB_USERNAME='${{ secrets.DB_USERNAME }}'" >> .env
          echo "BLOB_CONNECTION_STRING='${{ secrets.BLOB_CONNECTION_STRING }}'" >> .env
          echo "JWT_SECRET='${{ secrets.JWT_SECRET }}'" >> .env
          echo "EMAIL_CONNECTION_STRING='${{ secrets.EMAIL_CONNECTION_STRING }}'" >> .env
          cd ..

      - name: 'Run backend unit tests'
        run: |
          cd backend
          yarn install
          yarn run test

  build-backend:
    runs-on: ubuntu-latest
    needs: [test-backend]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ secrets.IMAGE_USERNAME }}
          password: ${{ secrets.IMAGE_TOKEN }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          secrets: |
            "DB_HOST='${{ secrets.DB_HOST }}'"
            "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'"
            "ENVIRONMENT='${{ secrets.ENVIRONMENT }}'"
            "DB_USERNAME='${{ secrets.DB_USERNAME }}'"
            "BLOB_CONNECTION_STRING='${{ secrets.BLOB_CONNECTION_STRING }}'"
            "JWT_SECRET='${{ secrets.JWT_SECRET }}'"
          push: false
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}-backend-pr
          file: ./backend/Dockerfile

  build-frontend:
    runs-on: ubuntu-latest
    needs: [test-frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ secrets.IMAGE_USERNAME }}
          password: ${{ secrets.IMAGE_TOKEN }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          secrets: |
            "REACT_APP_ENVIRONMENT='${{ secrets.ENVIRONMENT }}'"
          push: false
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}-frontend-pr
          file: ./frontend/Dockerfile
