name: Pull Request Checks

env:
  AZURE_WEBAPP_NAME: asd-backend  # set this to the name of your Azure Web App

on: [pull_request]

permissions:
  contents: read

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16.10.0
      - run: |
          cd frontend
          yarn install
          yarn run test

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ secrets.IMAGE_USERNAME }}
          password: ${{ secrets.IMAGE_TOKEN }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Copy over environment variables
        run: |
          cd backend
          echo "DB_HOST='${{ secrets.DB_HOST }}'" > .env
          echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> .env
          echo "DB_NAME='${{ secrets.DB_NAME }}'" >> .env
          echo "DB_USERNAME='${{ secrets.DB_USERNAME }}'" >> .env
          cd ..

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}-backend-pr
          file: ./backend/Dockerfile

  build-frontend:
    runs-on: ubuntu-latest
    needs: [test-frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ secrets.IMAGE_USERNAME }}
          password: ${{ secrets.IMAGE_TOKEN }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          secrets: |
            "DB_HOST='${{ secrets.DB_HOST }}'"
            "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'"
            "ENVIRONMENT='${{ secrets.ENVIRONMENT }}'"
            "DB_USERNAME='${{ secrets.DB_USERNAME }}'"
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}-frontend-pr
          file: ./frontend/Dockerfile
